/*****************************************************************************
* Model: blinky.qm
* File:  ./blinky.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/0) .................................................................*/
#include "qp_port.h"
#include "project.h"
#include "bsp.h"

Q_DEFINE_THIS_FILE

/* Active object class -----------------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct BlinkyTag {
/* protected: */
    QActive super;
    QTimeEvt timeEvt;
} Blinky;

/* protected: */
static QState Blinky_initial(Blinky * const me, QEvt const * const e);
static QState Blinky_off(Blinky * const me, QEvt const * const e);
static QState Blinky_on(Blinky * const me, QEvt const * const e);


/* Local objects -----------------------------------------------------------*/
static Blinky l_blinky;  /* the single instance of the Blinky active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Blinky = &l_blinky.super;         /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/2) .................................................................*/
void Blinky_ctor(void) {
        Blinky *me = &l_blinky;

        QActive_ctor(&me->super, Q_STATE_CAST(&Blinky_initial));
        QTimeEvt_ctor(&me->timeEvt, TIMEOUT_SIG);
}
/* @(/1/0) .................................................................*/
/* @(/1/0/1) ...............................................................*/
/* @(/1/0/1/0) */
static QState Blinky_initial(Blinky * const me, QEvt const * const e) {
    QTimeEvt_postEvery(
        &me->timeEvt,
        (QActive *)me,
        BSP_TICKS_PER_SEC/2);
    return Q_TRAN(&Blinky_off);
}
/* @(/1/0/1/1) .............................................................*/
static QState Blinky_off(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/1/1) */
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/1/1/0) */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/0/1/2) .............................................................*/
static QState Blinky_on(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/1/2) */
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/1/2/0) */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}


